/*
 * This source file was generated by the Gradle 'init' task
 */
package com.example.chat;

import org.junit.jupiter.api.Assertions;
import org.junit.jupiter.api.Test;

class AppTest {

    @Test
    public void appHasAGreeting() {
        Assertions.assertTrue(true, () -> "");
    }

}
